version: '3'

networks:
  merlinFace:

services:
  web:
    image: nginx:stable-alpine
    container_name: nginx_merlin_face_app
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - merlinFace

  mysql:
    platform: linux/amd64
    image: mysql:8.0.25
    container_name: mysql_merlin_face_app
    restart: unless-stopped
    ports:
      - "3319:3306"
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: merlin_face_app
      MYSQL_USER: merlin_face_app
      MYSQL_PASSWORD: merlin_face_app
      MYSQL_ROOT_PASSWORD: merlin_face_app
    networks:
      - merlinFace

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php_merlin_face_app
    volumes:
    - .:/var/www/html
    ports:
    - "9003:9000"
    networks:
      - merlinFace
